version: '3'
services:
  redis-master:
    image: ghcr.io/tambinos/m347/redis-master:v2
    container_name: redis-master
    ports:
      - "6379:6379"

  redis-slave:
    image: ghcr.io/tambinos/m347/redis-slave:v2
    container_name: redis-slave
    depends_on:
      - redis-master
    ports:
      - "6380:6379"

  todo-app:
    image: ghcr.io/tambinos/m347/todo-app:v2
    container_name: todo-app
    depends_on:
      - redis-master
    ports:
      - "3000:3000"
