apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-deployment
  namespace: play
spec:
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      labels:
        app: catalog        
    spec:
      serviceAccountName: catalog-serviceaccount
      containers:
        - name: catalog
          image: git-registry.gibb.ch/thomas.staub/microservices/play.catalog:1.0
          env:
            - name: MongoDbSettings__Host
              value: mongo
            - name: RabbitMQSettings__Host
              value: rabbitmq
            - name: SeqSettings__Host
              value: seq           
            - name: AllowedOrigins
              value: http://host.docker.internal               
          resources:
            limits:
              memory: "128Mi"
              cpu: "150m"
          ports:
            - containerPort: 80
          

---
apiVersion: v1
kind: Service
metadata:
  name: catalog-service
  namespace: play
spec:
  type: LoadBalancer
  selector:
    app: catalog
  ports:
    - port: 5000
      targetPort: 80

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: catalog-serviceaccount
  namespace: play

