apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend2-deployment
  namespace: play
spec:
  selector:
    matchLabels:
      app: frontend2
  template:
    metadata:
      labels:
        app: frontend2        
    spec:
      serviceAccountName: frontend2-serviceaccount
      containers:
        - name: frontend2
          image: git-registry.gibb.ch/thomas.staub/microservices/play.frontendv2:1.0               
          resources:
            limits:
              memory: "128Mi"
              cpu: "150m"           
          ports:
            - containerPort: 80
          

      

---
apiVersion: v1
kind: Service
metadata:
  name: frontend2-service
  namespace: play
spec:
  type: LoadBalancer
  selector:
    app: frontend2
  ports:
    - name: http
      protocol: TCP
      port: 5008
      targetPort: 80 

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend2-serviceaccount
  namespace: play
---

