apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-deployment
  namespace: play
spec:
  selector:
    matchLabels:
      app: inventory
  template:
    metadata:
      labels:
        app: inventory      
    spec:
      serviceAccountName: inventory-serviceaccount
      containers:
        - name: inventory
          image: git-registry.gibb.ch/thomas.staub/microservices/play.inventory:1.0
          env:
            - name: MongoDbSettings__Host
              value: mongo
            - name: RabbitMQSettings__Host
              value: rabbitmq
            - name: SeqSettings__Host
              value: seq                       
          resources:
            limits:
              memory: "128Mi"
              cpu: "150m"
          ports:
            - containerPort: 80
          

---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: play
spec:
  type: LoadBalancer
  selector:
    app: inventory
  ports:
    - port: 5004
      targetPort: 80 

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: inventory-serviceaccount
  namespace: play

---
