global:
  scrape_interval: 5s
scrape_configs:
  - job_name: "otel"
    static_configs:
      - targets: [
        "host.docker.internal:5006",
        "host.docker.internal:5002",
        "host.docker.internal:5000",
        "host.docker.internal:5004"]