apiVersion: apps/v1
kind: Deployment
metadata:
  name: trading-deployment
spec:
  selector:
    matchLabels:
      app: trading
  template:
    metadata:
      labels:
        app: trading        
    spec:
      serviceAccountName: trading-serviceaccount
      containers:
        - name: trading
          image: git.gibb.ch:5050/thomas.staub/microservices/play.trading:1.0
          env:
            - name: MongoDbSettings__Host
              value: mongo
            - name: RabbitMQSettings__Host
              value: rabbitmq            
          resources:
            limits:
              memory: "128Mi"
              cpu: "150m"
          ports:
            - containerPort: 5006
          livenessProbe:
            httpGet:
              path: /health/live
              port: 5006
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 5006
            initialDelaySeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: trading-service
spec:
  type: ClusterIP
  selector:
    app: trading
  ports:
    - port: 80
      targetPort: 5006

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: trading-serviceaccount
