{
 "title": "Play.Economy",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Purchse Failed",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "PurchaseFailed_total{job=\"otel\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Purchse Successfull",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "PurchaseSuccess_total{job=\"otel\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Purchse Started",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "PurchaseStarted_total{job=\"otel\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}